# Generated by Django 5.2.4 on 2025-08-14 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiniela',
            name='mostrar_elecciones',
        ),
    ]
