# Generated by Django 5.2.4 on 2025-08-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_equipo_partido_fecha_alter_partido_equipo_local_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiniela',
            name='mostrar_elecciones',
            field=models.BooleanField(default=False),
        ),
    ]
