# Generated by Django 5.2.4 on 2025-08-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_quiniela_mostrar_elecciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiniela',
            name='mostrar_elecciones',
            field=models.BooleanField(default=False),
        ),
    ]
