# Generated by Django 5.2.4 on 2025-08-20 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_quiniela_mostrar_elecciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='resultado_real',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partidos_ganados', to='api.equipo'),
        ),
    ]
