# Generated by Django 5.2.4 on 2025-08-20 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_partido_resultado_real'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleccion',
            name='equipo_elegido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipo'),
        ),
    ]
